// { text: "Document Request", value: "DocumentRequest"},
// { text: "General", value: "General"},
// { text: "Insurance Verification", value: "InsuranceVerification"},
// { text: "Medicare Denial", value: "MedicareDenianl"},
// { text: "Refill", value: "Refill"},
// { text: "New Referral Confirmation", value:"NewReferralConfirmation"}
// { text: "Authorization Denial", value:"AuthorizationDenial"}
// { text: "Treatment Note", value:"TreatmentNote"}

export const DocumentRequest = {
    attention: "",
    sendToPhone: "",
    outboundFax: "",
    subject: "",
    fromName: "",
    fromPhone: "",
    fromFax: "",
    fromDate: "",
    patientFirstName: "",
    patientLastName: "",
    dob: "",
    faxNotes: "",
}
export const General = {
    attention: "",
    sendToPhone: "",
    outboundFax: "",
    subject: "",
    fromName: "",
    fromPhone: "",
    fromFax: "",
    fromDate: "",
    patientFirstName: "",
    patientLastName: "",
    dob: "",
    faxNotes: "",
}
export const InsuranceVerification = {
    attention: "",
    sendToPhone: "",
    outboundFax: "",
    subject: "",
    fromName: "",
    fromPhone: "",
    fromFax: "",
    fromDate: "",
    patientFirstName: "",
    patientLastName: "",
    dob: "",
    referralOrderName: "",
    insuranceCompanyName: "",
    priorAuthSubmittedDate: "",
    priorAuthInAuthStatus: "",
    faxNotes: "",
}
export const MedicareDenianl = {
    attention: "",
    sendToPhone: "",
    outboundFax: "",
    subject: "",
    fromName: "",
    fromPhone: "",
    fromFax: "",
    fromDate: "",
    patientFirstName: "",
    patientLastName: "",
    dob: "",
    faxNotes: "",
}
export const Refill = {
    attention: "",
    sendToPhone: "",
    outboundFax: "",
    subject: "",
    fromName: "",
    fromPhone: "",
    fromFax: "",
    fromDate: "",
    patientFirstName: "",
    patientLastName: "",
    dob: "",
    cellphoneNumber: "",
    email: "",
    prescName: "",
    prescAddress: "",
    officeContact: "",
    officePhone: "",
    officeFax: "",
    npiNumber: "",
    taxIdNo: "",
    orderName: "",
    patientWeightLB: "",
    approvedDosage: "",
    referralOrderPreMedications: "",
    approvedDosagePreMed: "",
    numTreatments: "",
    faxNotes: "",
}
export const NewReferralConfirmation = {
    attention: "",
    sendToPhone: "",
    outboundFax: "",
    subject: "",
    fromName: "",
    fromPhone: "",
    fromFax: "",
    fromDate: "",
    patientFirstName: "",
    patientLastName: "",
    dob: "",
    faxNotes: "",
}
export const AuthorizationDenial = {
    attention: "",
    sendToPhone: "",
    outboundFax: "",
    subject: "",
    fromName: "",
    fromPhone: "",
    fromFax: "",
    fromDate: "",
    patientFirstName: "",
    patientLastName: "",
    dob: "",
    faxNotes: "",
}
