export const Constants = {
    ErrorMessage: {
        //selectDrug_REQUIRED: "Drug Selection Must not be Empty",
        //gender_REQUIRED: "Gender Selection Must not be Empty",
        FirstName_REQUIRED: "required",
        lastname_REQUIRED: "required",
        dateOfBirth_REQUIRED: "required",
        //Address_REQUIRED: "Address Must not be empty",
        //State_REQUIRED: "City,State,Zipcode  Must not be empty",
        //SSN_REQUIRED: "SSN Must not be Empty",
        PhoneNumber_REQUIRED: "required",
        //EMAIL_REQUIRED: "Email Must not be empty",
        EMAIL_REGX: "Email Must be a valid address",
        PASSWROD_REQUIRD: "Email Must not be empty",
        //Zip_REQUIRED: "Zip Must not be empty",
        //City_REQUIRED: "City Must not be empty",
        //altContactFirstName_REQUIRED: "Alternate First Name Must not be empty",
        //altContactLastName_REQUIRED: "Alternate Last Name Must not be empty",
        //altContactPhone_REQUIRED: "Alternate First Name Must not be empty",
        Alpha_Required: "Only Alphabets are allowed",
        Numeric_Required: "Only Numerals are allowed",
        //preferredLanguage_REQUIRED: "please enter Preferred Language",
        //planName_REQUIRED: "Plan Name is Required",
        //Name_REQUIRED: "Name is Required",
        state_REQUIRED: "please select a state",
        insuranceExpireDate_REQUIRED: "Insurance Exp. Date Must not be Empty",
        prescFirstName_REQUIRED: "First Name Must not be empty",
        prescLastName_REQUIRED: "Last Name Must not be empty",
        //officePhNo_REQUIRED: "Phone No. Must not be empty",
        FaxNo_REQUIRED: "Fax No. Must not be empty",
        siteInstName_REQUIRED: "Site Name Must not be empty",
        taxIdNo_REQUIRED: "Tax. ID Must not be empty",
        npiNo_REQUIRED: "NPI No. Must not be empty",
        orderDate_REQUIRED: "Order Exp. Date Must not be empty",
        primaryDiag_REQUIRED: "Primary Diagnosis is Required",
        specPharmName_REQUIRED: "Specialty Pharmacy Name is Required",
        SSN_No_REQUIRED: "SSN No Must not be empty",
        reasNewTherapy_REQUIRED: "Reason is Required",
        primaryDiagnosisInfo_REQUIRED: "Primary Diagnosis is Required",
        infusionProvName_REQUIRED: "Name is Required",
        drug_REQUIRED: "Drug Name is Required",
        dosage_REQUIRED: "Dosage is Required",
        frequency_REQUIRED: "Frequency is Required",
        doctorName_Required: "Physician Name is Required",
        orderDates_REQUIRED: "Order Date is Required",
        npiNumber_REQUIRED: "NPI is Required",
        is_REQUIRED: "Required",
        polIdNum_REQUIRED: "Required",
        insName_REQUIRED: "Required",
    },
    Label: {
        PRESCRIPTION_FOR: 'PRESCRIPTION FOR'
    },
    DATE: {
        SHORTDATE: 'MM-DD-YYYY',
        LONGFORMAT: 'YYYY-DD-MM',
        STARTYEARFORMAT: 'YYYY-MM-DD',
        DATEFORMATWITHTIME: 'MM/DD/YYYY hh:mm a',
        DATEFORMATMMDDYYYY: 'MM/DD/YYYY',
    }
};

