const question1 = {
    title: "CONSTITUTIONAL",
    question1_1: Boolean,
    question1_2: String,
    question1_3: Boolean,
    question1_4: String,
    question1_5: Boolean,
    question1_6: String, 
}
const question2 = {
    title: "CARDIOVASCULAR",
    question2_1: Boolean,
    question2_2: String,
    question2_3: Boolean,
    question2_4: String,
    question2_5: Boolean,
    question2_6: String,
    question2_7: Boolean,
    question2_8: String,
}
const question3 = {
    title: "NEUROLOGICAL",
    question3_1: Boolean,
    question3_2: String,
    question3_3: Boolean,
    question3_4: String,
    question3_5: Boolean,
    question3_6: String,
    question3_7: Boolean,
    question3_8: String,
    question3_9: Boolean,
    question3_10: String,
    question3_11: Boolean,
    question3_12: String,
}
const question4 = {
    title: "SKIN",
    question4_1: Boolean,
    question4_2: String,
    question4_3: Boolean,
    question4_4: String,
}
const question5 = {
    title: "EYES/EARS/NOSE/THROAT",
    question5_1: Boolean,
    question5_2: String,
    question5_3: Boolean,
    question5_4: String,
    question5_5: Boolean,
    question5_6: String,
    question5_7: Boolean,
    question5_8: String,
}
const question6 = {
    title: "RESPIRATORY",
    question6_1: Boolean,
    question6_2: String,
    question6_3: Boolean,
    question6_4: String,
    question6_5: Boolean,
    question6_6: String,
    question6_7: Boolean,
    question6_8: String,
    question6_9: Boolean,
    question6_10: String,
} 
const question7 = {
    title: "GENITAL/URINARY",
    question7_1: Boolean,
    question7_2: String,
    question7_3: Boolean,
    question7_4: String,
    question7_5: Boolean,
    question7_6: String,
    question7_7: Boolean,
    question7_8: String,
}
const question8 = {
    title: "MUSCULOSKELETAL",
    question8_1: Boolean,
    question8_2: String,
    question8_3: Boolean,
    question8_4: String,
    question8_5: Boolean,
    question8_6: String,
}
const question9 = {
    title: "GASTROINTESTINAL",
    question9_1: Boolean,
    question9_2: String,
    question9_3: Boolean,
    question9_4: String,
    question9_5: Boolean,
    question9_6: String,
    question9_7: Boolean,
    question9_8: String,
}
const question10 = {
    title: "PSYCHOLOGICAL",
    question10_1: Boolean,
    question10_2: String,
    question10_3: Boolean,
    question10_4: String,
    question10_5: Boolean,
    question10_6: String,
    question10_7: Boolean,
    question10_8: String,
}
const question11 = {
    title: "FEMALE",
    question11_1: Boolean,
    question11_2: String,
    question11_3: Boolean,
    question11_4: String,
    question11_5: Boolean,
    question11_6: String,
    question11_7: Boolean,
    question11_8: String,
}
const question12 = {
    title: "TYSABRI",
    question12_1: Boolean,
    question12_2: String,
    question12_3: Boolean,
    question12_4: String,
}