export const sampleProducts = [
    {
        "ProductID": 1,
        "ProductName": "Chai",
        "CallReason": "Web Enrollment",
        "Purpose": "Information",
        "FollowUpDate": "10/01/2020",
        "PatientName": "John Smith",
        "Status": "Incomplete",
        "SupplierID": 1,
        "CategoryID": 1,
        "QuantityPerUnit": "10 boxes x 20 bags",
        "UnitPrice": 18,
        "UnitsInStock": 39,
        "UnitsOnOrder": 0,
        "ReorderLevel": 10,
        "Discontinued": false,
        "Category": {
            "CategoryID": 1,
            "CategoryName": "Beverages",
            "Description": "Soft drinks, coffees, teas, beers, and ales"
        },
        "FirstOrderedOn": '01/01/2021'
    },
    {
        "ProductID": 2,
        "ProductName": "Chang",
        "CallReason": "Web Enrollment",
        "Purpose": "Information",
        "FollowUpDate": "10/01/2020",
        "PatientName": "Smith",
        "Status": "Progress",
        "SupplierID": 1,
        "CategoryID": 1,
        "QuantityPerUnit": "24 - 12 oz bottles",
        "UnitPrice": 19,
        "UnitsInStock": 17,
        "UnitsOnOrder": 40,
        "ReorderLevel": 25,
        "Discontinued": false,
        "Category": {
            "CategoryID": 1,
            "CategoryName": "Beverages",
            "Description": "Soft drinks, coffees, teas, beers, and ales"
        },
        "FirstOrderedOn": '01/01/2021'
    },
    {
        "ProductID": 3,
        "ProductName": "Aniseed Syrup",
        "CallReason": "Web Enrollment",
        "Purpose": "Information",
        "FollowUpDate": "08/11/2020",
        "PatientName": "Jacob",
        "Status": "Incomplete",
        "SupplierID": 1,
        "CategoryID": 2,
        "QuantityPerUnit": "12 - 550 ml bottles",
        "UnitPrice": 10,
        "UnitsInStock": 13,
        "UnitsOnOrder": 70,
        "ReorderLevel": 25,
        "Discontinued": false,
        "Category": {
            "CategoryID": 2,
            "CategoryName": "Condiments",
            "Description": "Sweet and savory sauces, relishes, spreads, and seasonings"
        },
        "FirstOrderedOn": '01/01/2021'
    },
    {
        "ProductID": 4,
        "ProductName": "Chef Anton's Cajun Seasoning",
        "CallReason": "Web Enrollment",
        "Purpose": "Information",
        "FollowUpDate": "07/21/2020",
        "PatientName": "Williams",
        "Status": "Progress",
        "SupplierID": 2,
        "CategoryID": 2,
        "QuantityPerUnit": "48 - 6 oz jars",
        "UnitPrice": 22,
        "UnitsInStock": 53,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": false,
        "Category": {
            "CategoryID": 2,
            "CategoryName": "Condiments",
            "Description": "Sweet and savory sauces, relishes, spreads, and seasonings"
        },
        "FirstOrderedOn": '01/01/2021'
    },
    {
        "ProductID": 5,
        "ProductName": "Chef Anton's Gumbo Mix",
        "CallReason": "Web Enrollment",
        "Purpose": "Information",
        "FollowUpDate": "08/01/2020",
        "PatientName": "Mike",
        "Status": "Incomplete",
        "SupplierID": 2,
        "CategoryID": 2,
        "QuantityPerUnit": "36 boxes",
        "UnitPrice": 21.35,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": true,
        "Category": {
            "CategoryID": 2,
            "CategoryName": "Condiments",
            "Description": "Sweet and savory sauces, relishes, spreads, and seasonings"
        },
        "FirstOrderedOn": '01/01/2021'
    },
    {
        "ProductID": 6,
        "ProductName": "Grandma's Boysenberry Spread",
        "CallReason": "Web Enrollment",
        "Purpose": "Information",
        "FollowUpDate": "09/01/2020",
        "PatientName": "Surya",
        "Status": "Progress",
        "SupplierID": 3,
        "CategoryID": 2,
        "QuantityPerUnit": "12 - 8 oz jars",
        "UnitPrice": 25,
        "UnitsInStock": 120,
        "UnitsOnOrder": 0,
        "ReorderLevel": 25,
        "Discontinued": false,
        "Category": {
            "CategoryID": 2,
            "CategoryName": "Condiments",
            "Description": "Sweet and savory sauces, relishes, spreads, and seasonings"
        },
        "FirstOrderedOn": '01/01/2021'
    },
    {
        "ProductID": 7,
        "ProductName": "Uncle Bob's Organic Dried Pears",
        "CallReason": "Web Enrollment",
        "Purpose": "Information",
        "FollowUpDate": "09/25/2020",
        "PatientName": "David",
        "Status": "Incomplete",
        "SupplierID": 3,
        "CategoryID": 7,
        "QuantityPerUnit": "12 - 1 lb pkgs.",
        "UnitPrice": 30,
        "UnitsInStock": 15,
        "UnitsOnOrder": 0,
        "ReorderLevel": 10,
        "Discontinued": false,
        "Category": {
            "CategoryID": 7,
            "CategoryName": "Produce",
            "Description": "Dried fruit and bean curd"
        },
        "FirstOrderedOn": '01/01/2021'
    },
    {
        "ProductID": 8,
        "ProductName": "Northwoods Cranberry Sauce",
        "CallReason": "Web Enrollment",
        "Purpose": "Information",
        "FollowUpDate": "06/01/2020",
        "PatientName": "Scott",
        "Status": "Complete",
        "SupplierID": 3,
        "CategoryID": 2,
        "QuantityPerUnit": "12 - 12 oz jars",
        "UnitPrice": 40,
        "UnitsInStock": 6,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": false,
        "Category": {
            "CategoryID": 2,
            "CategoryName": "Condiments",
            "Description": "Sweet and savory sauces, relishes, spreads, and seasonings"
        },
        "FirstOrderedOn": '01/01/2021'
    },
    {
        "ProductID": 9,
        "ProductName": "Mishi Kobe Niku",
        "CallReason": "Web Enrollment",
        "Purpose": "Information",
        "FollowUpDate": "07/19/2020",
        "PatientName": "Justin",
        "Status": "Progress",
        "SupplierID": 4,
        "CategoryID": 6,
        "QuantityPerUnit": "18 - 500 g pkgs.",
        "UnitPrice": 97,
        "UnitsInStock": 29,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": true,
        "Category": {
            "CategoryID": 6,
            "CategoryName": "Meat/Poultry",
            "Description": "Prepared meats"
        },
        "FirstOrderedOn": '01/01/2021'
    },
    {
        "ProductID": 10,
        "ProductName": "Ikura",
        "CallReason": "Web Enrollment",
        "Purpose": "Information",
        "FollowUpDate": "08/01/2020",
        "PatientName": "Colin",
        "Status": "progress",
        "SupplierID": 4,
        "CategoryID": 8,
        "QuantityPerUnit": "12 - 200 ml jars",
        "UnitPrice": 31,
        "UnitsInStock": 31,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": false,
        "Category": {
            "CategoryID": 8,
            "CategoryName": "Seafood",
            "Description": "Seaweed and fish"
        },
        "FirstOrderedOn": '01/01/2021'
    },
    {
        "ProductID": 11,
        "ProductName": "Ikura",
        "CallReason": "Web Enrollment",
        "Purpose": "Information",
        "FollowUpDate": "08/01/2021",
        "PatientName": "James",
        "Status": "Incomplete",
        "SupplierID": 4,
        "CategoryID": 8,
        "QuantityPerUnit": "12 - 200 ml jars",
        "UnitPrice": 31,
        "UnitsInStock": 31,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": false,
        "Category": {
            "CategoryID": 8,
            "CategoryName": "Seafood",
            "Description": "Seaweed and fish"
        },
        "FirstOrderedOn": '01/01/2021'
    }
];